jobs = {
    "Python Developer": ["python", "flask", "django", "sql", "api"],
    "Web Developer": ["html", "css", "javascript", "bootstrap"],
    "Frontend Developer": ["html", "css", "javascript", "react"],
    "Backend Developer": ["python", "django", "flask", "api", "sql"],
    "Full Stack Developer": ["html", "css", "javascript", "python", "sql"],
    "Data Analyst": ["python", "pandas", "excel", "sql"],
    "Data Scientist": ["python", "pandas", "numpy", "machine learning"],
    "Machine Learning Engineer": ["python", "numpy", "pandas", "ml"],
    "AI Engineer": ["python", "ml", "deep learning", "nlp"],
    "Software Engineer": ["java", "python", "dsa", "oop"],
    "Java Developer": ["java", "spring", "hibernate", "sql"],
    "C++ Developer": ["c++", "dsa", "oop"],
    "Mobile App Developer": ["java", "kotlin", "android"],
    "Android Developer": ["java", "kotlin", "android", "xml"],
    "UI/UX Designer": ["figma", "design", "prototyping"],
    "Graphic Designer": ["photoshop", "illustrator", "creativity"],
    "DevOps Engineer": ["docker", "kubernetes", "linux", "ci/cd"],
    "Cloud Engineer": ["aws", "azure", "cloud", "linux"],
    "Cybersecurity Analyst": ["networking", "security", "linux"],
    "Ethical Hacker": ["networking", "security", "kali linux"],
    "Database Administrator": ["sql", "database", "mysql"],
    "Game Developer": ["c++", "unity", "game design"],
    "Blockchain Developer": ["blockchain", "solidity", "ethereum"],
    "Digital Marketer": ["seo", "marketing", "analytics"],
    "Content Writer": ["writing", "seo", "research"]
}
